name: "Docs build job"
description: "Build the documentation."
runs:
  using: "composite"
  steps:
    - run: sphinx-apidoc -o docs/source src/dgbowl_schemas -T -M -E -f
      shell: bash
    - run: sphinx-build -W -b html docs/source public/master
      shell: bash
